### PR TITLE
added optional resource name for workflows

### PR DESCRIPTION
**Pull request by jakeymac**
Added a resource name field to the new workflow form, now displays this optional resource name in the workflow views.

### CODE REVIEW

**Review by swainn — CHANGES_REQUESTED** [review]
- [x] Change to use "Description" instead of "Resource Name".
- [ ] Display on separate line and only show one line of it, but full text available on hovering over it.

**Comment by jakeymac** [comment]
Last commit makes change to use "description" @swainn

**Comment by jakeymac** [comment]
description_field_screenshot
This is how the add_workflow form currently looks. Do we maybe want to make the description field a bit larger to fit more lines of text?

**Review by swainn — APPROVED** [review]
I love it!

**Pull request merged**
